import Head from 'next/head'
import {
    Box, Button,
    Card,
    CardContent,
    Container,
    FormControl,
    FormHelperText,
    InputLabel, OutlinedInput, styled,
} from "@mui/material";
import {useEffect, useState} from "react";
import TextMaskCustom from "../components/TextMaskCustom";

const Btn = styled(Button)({
    outline: 'none',
    width: '80px',
    height: '30px',
    borderRadius: '5px',
    border: '1px solid grey',
    cursor: 'pointer',
    position: 'relative',
    overflow: 'hidden',
    color: '#000',
    '&:before': {
        content: '""',
        position: 'absolute',
        top: 0,
        left: '-100%',
        width: '200%',
        height: '100%',
        background: 'linear-gradient(to right, lightgreen 0%,lightgreen 50%,#fff 50%,#fff 100%)',
        transition: 'left .7s',
    },
    '&:hover:before':{
        left: '0'
    }
})

export default function Home() {
    const [values, setValues] = useState({
        CardNumber: '',
        ExpDate: '',
        Cvv: '',
        Amount: '',
    });
    const [error, setError] = useState({
        CardNumber: false,
        ExpDate: false,
        Cvv: false,
        Amount: false,
    })
    const [focus, setFocus] = useState({
        CardNumber: false,
        ExpDate: false,
        Cvv: false,
        Amount: false,
    })
    const [Disabled, setDisabled] = useState(true)
    const handleChange = (event) => {
        setValues({
            ...values,
            [event.target.name]: event.target.value,
        });
    };
    useEffect(()=>{
        if(focus.CardNumber && values.CardNumber.replace(/[^0-9]/g, '').length < 16){
            setError({...error, CardNumber: true})
        }else {
            setError({...error, CardNumber: false})
        }
    }, [values.CardNumber])
    useEffect(()=>{
        if(focus.ExpDate && values.ExpDate.length < 7){
            setError({...error, ExpDate: true})
        }else {
            setError({...error, ExpDate: false})
        }
    }, [values.ExpDate])
    useEffect(()=>{
        if(focus.Cvv && values.Cvv.length < 3){
            setError({...error, Cvv: true})
        }else {
            setError({...error, Cvv: false})
        }
    }, [values.Cvv])
    useEffect(()=>{
        if(focus.Amount && !values.Amount.length){
            setError({...error, Amount: true})
        }else {
            setError({...error, Amount: false})
        }
        console.log(Disabled)
    }, [values.Amount])
    useEffect(()=>{
        if(!error.CardNumber && values.CardNumber.length
            && !error.ExpDate && values.ExpDate.length
            && !error.Cvv && values.Cvv.length
            && !error.Amount && values.Amount.length
        ){
            setDisabled(false)
        }else {
            setDisabled(true)
        }
    }, [error])
    const OnFocus = (e)=>{
        setFocus({
            ...focus,
            [e.target.id]: true
        })
    }
    const Submit = async (e)=>{
        e.preventDefault()
        let data = {...values, CardNumber: values.CardNumber.replace(/[^0-9]/g, '')}
        const res = await fetch('/api/redis', {method: 'POST', body: JSON.stringify(data)})
        const resData = await res.json()
        console.log(resData)
    }
  return (
    <Container>
      <Head>
          <title>Card validation</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
          <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
      </Head>
      <main style={{height: '100vh', display: 'flex', alignItems: 'center',justifyContent: 'center',}}>
          <Box sx={{}}>
              <Card sx={{maxWidth: 345}}>
                  <CardContent>
                      <Box component="form" vallidate sx={{width: '320'}}>
                          <FormControl error={error.CardNumber} sx={{marginBottom: 2, width: '100%', }}
                                       onFocus={OnFocus}>
                              <InputLabel htmlFor="CardNumber">Номер карты</InputLabel>
                              <OutlinedInput
                                  label={'Номер карты'}
                                  value={values.CardNumber}
                                  onChange={handleChange}
                                  name="CardNumber"
                                  id="CardNumber"
                                  inputComponent={TextMaskCustom}
                              />
                              <FormHelperText>Введите номер
                                  карты {values.CardNumber.replace(/[^0-9]/g, '').length}/16</FormHelperText>
                          </FormControl>
                          <FormControl error={error.ExpDate} sx={{marginBottom: 2, width: '100%'}}
                                       onFocus={OnFocus}>
                              <InputLabel htmlFor="ExpDate">Срок действия</InputLabel>
                              <OutlinedInput
                                  label={'Срок действия'}
                                  value={values.ExpDate}
                                  onChange={handleChange}
                                  name="ExpDate"
                                  id="ExpDate"
                                  inputComponent={TextMaskCustom}
                              />
                              <FormHelperText>формат даты MM/YYYY</FormHelperText>
                          </FormControl>
                          <FormControl error={error.Cvv} sx={{marginBottom: 2, width: '100%'}}
                                       onFocus={OnFocus}>
                              <InputLabel htmlFor="Cvv">CVV</InputLabel>
                              <OutlinedInput
                                  label={'CVV'}
                                  value={values.Cvv}
                                  onChange={handleChange}
                                  name="Cvv"
                                  id="Cvv"
                                  inputComponent={TextMaskCustom}
                              />
                              <FormHelperText>CVV {values.Cvv.length}/3</FormHelperText>
                          </FormControl>
                          <FormControl error={error.Amount} sx={{marginBottom: 2, width: '100%'}}
                                       onFocus={OnFocus}>
                              <InputLabel htmlFor="Amount">Сумма</InputLabel>
                              <OutlinedInput
                                  label={'Сумма'}
                                  value={values.Amount}
                                  onChange={handleChange}
                                  name="Amount"
                                  id="Amount"
                                  inputComponent={TextMaskCustom}
                              />
                              <FormHelperText>Сумма</FormHelperText>
                          </FormControl>
                          <div style={{display: "flex", justifyContent: 'end'}}>
                              <Btn disabled={Disabled}  onClick={Submit}><span style={{position: "relative"}}>Submit</span></Btn>
                          </div>
                      </Box>
                  </CardContent>
              </Card>
          </Box>
      </main>
      <footer>
      </footer>
    </Container>
  )
}
