import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Card, CardContent, CardMedia, Container, FormControl, Input, InputLabel, TextField} from "@mui/material";
import {useState} from "react";
import TextMaskCustom from "../components/TextMaskCustom";

export default function Home() {
    const [values, setValues] = useState({
        CardNumber: '',
        ExpirationDate: '',
    });
    const handleChange = (event) => {
        setValues({
            ...values,
            [event.target.name]: event.target.value,
        });
    };
    const mask = "(#00) 000-0000"
  return (
    <Container>
      <Head>
          <title>Card validation</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
          <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
      </Head>
      <main>
        <Card sx={{ maxWidth: 345 }}>
            <CardMedia
                component="img"
                image="/bank-card.jpg"
                alt="Bank card"
            />
            <CardContent>
                <FormControl variant="standard">
                    <InputLabel htmlFor="CardNumber">Card number</InputLabel>
                    <Input
                        value={values.CardNumber}
                        onChange={handleChange}
                        name="CardNumber"
                        id="CardNumber"
                        inputComponent={TextMaskCustom}
                    />
                </FormControl>
                <FormControl variant="standard">
                    <InputLabel htmlFor="ExpirationDate">Expiration date</InputLabel>
                    <Input
                        value={values.ExpirationDate}
                        onChange={handleChange}
                        name="ExpirationDate"
                        id="ExpirationDate"
                        inputComponent={TextMaskCustom}
                    />
                </FormControl>
            </CardContent>
        </Card>
      </main>
      <footer>
        Footer
      </footer>
    </Container>
  )
}
